export const chapters = [
  {
    number: 1,
    title: 'What is a Perceptron?',
    path: '/learn/what-is-a-perceptron',
    description: 'Biological neuron analogy, the mathematical model, inputs, weights, bias, and activation.',
    color: 'accent-blue',
    icon: '\uD83E\uDDE0',
    tags: ['Neuron Model', 'Weights', 'Bias'],
  },
  {
    number: 2,
    title: 'Decision Boundaries',
    path: '/learn/decision-boundaries',
    description: 'The equation w\u2081\u00B7x\u2081 + w\u2082\u00B7x\u2082 + b = 0 as a line, geometric intuition, and linear separability.',
    color: 'accent-green',
    icon: '\uD83D\uDCCA',
    tags: ['Boundary Line', 'Geometry', 'Linear Separability'],
    labLink: '/lab',
  },
  {
    number: 3,
    title: 'Activation Functions',
    path: '/learn/activation-functions',
    description: 'Hard limit, symmetrical hard limit, linear, sigmoid, and tanh. Why non-linearity matters.',
    color: 'accent-yellow',
    icon: '\u26A1',
    tags: ['Hard Limit', 'Sigmoid', 'Tanh'],
    labLink: '/lab',
  },
  {
    number: 4,
    title: 'The Perceptron Learning Rule',
    path: '/learn/learning-rule',
    description: 'Weight update rule, convergence theorem, the XOR problem, and a preview of multi-layer networks.',
    color: 'primary-light',
    icon: '\uD83C\uDFAF',
    tags: ['Weight Update', 'Convergence', 'XOR Problem'],
    labLink: '/lab',
  },
]
